# Generated by Django 3.0.8 on 2021-02-11 19:08

from django.db import migrations, models
import django.db.models.deletion

Visualizers = [
    ['stress','Stressor'],
    ['iv-curve','IV Curve'],
    ['el-image','Electroluminence image'],
    ['visual-inspection','Visual Inspection'],
    ['diode','Diode Test'],
    ['wet_leakage','Wet Leakage'],
    ['colorimeter','Colorimeter'],
    ['iam','Incidence Angle Measurement'],
    ['pan','PAN file'],
]

def addVisualizers(apps, schema_editor):
    Visualizer = apps.get_model("lsdb", "Visualizer")
    for row in Visualizers:
        vis = Visualizer.objects.create(name=row[0],description=row[1])
        vis.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0008_auto_20210115_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(addVisualizers),
        migrations.AlterField(
            model_name='userprofile',
            name='user_registration_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lsdb.UserRegistrationStatus'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='visualizer',
            index=models.Index(fields=['name'], name='lsdb_visual_name_c083b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visualizer',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='proceduredefinition',
            name='visualizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lsdb.Visualizer'),
            preserve_default=False,
        ),
    ]
