version: '3.7'

services:

  node:
    container_name: node
    tty: true
    build:
      context: ../../
      dockerfile: ./asimov/dev/Dockerfile-node
    volumes:
      - '../../webclient/:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    # environment:
      # - NODE_ENV=development
      # - REACT_APP_API_HOST=/api/1.0
      # - REACT_APP_API_MOCK=false
    links:
      - lsdb

  lsdb:
    build:
        context: ../../
        dockerfile: ./asimov/dev/Dockerfile-lsdb
    security_opt:
      - seccomp:unconfined
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../backend/:/usr/src/HaveBlue/backend
      - ../../lsdb/:/usr/src/HaveBlue/lsdb
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    links:
      - devdb

  devdb:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=supersecretpass
      - POSTGRES_DB=lsdbdevdb

volumes:
  postgres_data:
