# DEV-Local docker
FROM node:12.13.1-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_API_HOST http://localhost:8000/api/1.0
ENV REACT_APP_API_MOCK false
#ENV REACT_APP_API_MOCK_HOST /api/1.0
ENV REACT_APP_LSDB_BUILD DEVELOPMENT
COPY webclient/package.json /app/package.json
RUN npm install --only=prod --silent --legacy-peer-deps
RUN npm install react-scripts=@4.0.1 --only=prod -g --silent --legacy-peer-deps

# When we have a test deployment, we'll need this:
#COPY ./local_dev.env ./.env
# start app
CMD ["npm", "start"]
