version: '3.7'

services:

  lsdb:
    build:
        context: ../../
        dockerfile: ./asimov/dev/Dockerfile-lsdb
    security_opt:
      - seccomp:unconfined
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../backend/:/usr/src/HaveBlue/backend
      - ../../lsdb/:/usr/src/HaveBlue/lsdb
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    links:
      - devdb

  devdb:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=supersecretpass
      - POSTGRES_DB=lsdbdevdb

volumes:
  postgres_data:
