# Generated by Django 3.0.8 on 2020-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0002_auto_20201215_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecutionorder',
            name='execution_group_name',
            field=models.CharField(default='default name', max_length=128),
            preserve_default=False,
        ),
    ]
