# Generated by Django 3.0.8 on 2020-12-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0003_stepexecutionorder_execution_group_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stepexecutionorder',
            name='lsdb_stepex_executi_55f376_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stepexecutionorder',
            unique_together={('execution_group_name', 'execution_group_number', 'procedure_definition', 'step_definition')},
        ),
        migrations.AddIndex(
            model_name='stepexecutionorder',
            index=models.Index(fields=['execution_group_name', 'execution_group_number', 'procedure_definition', 'step_definition'], name='lsdb_stepex_executi_f822dc_idx'),
        ),
    ]
