# Generated by Django 3.0.8 on 2020-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0004_auto_20201218_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureresult',
            name='allow_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='allow_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stepexecutionorder',
            name='allow_skip',
            field=models.BooleanField(default=False),
        ),
    ]
