# Generated by Django 3.0.8 on 2021-01-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0005_auto_20201223_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedureresult',
            options={'ordering': ('linear_execution_group',)},
        ),
    ]
