# Generated by Django 3.0.8 on 2021-01-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0006_auto_20210108_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementresult',
            options={'ordering': ('report_order',)},
        ),
        migrations.RemoveIndex(
            model_name='stepresult',
            name='lsdb_stepre_procedu_055d6a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stepresult',
            unique_together={('name', 'procedure_result', 'execution_number', 'step_definition', 'test_step_result')},
        ),
        migrations.AddIndex(
            model_name='stepresult',
            index=models.Index(fields=['name', 'procedure_result', 'execution_number', 'step_definition', 'test_step_result'], name='lsdb_stepre_name_67487d_idx'),
        ),
    ]
