# Generated by Django 3.0.8 on 2021-01-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0007_auto_20210112_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepresult',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
