# Generated by Django 3.0.8 on 2021-02-22 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0009_auto_20210211_1908'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unittype',
            name='lsdb_unitty_manufac_415a1e_idx',
        ),
        migrations.AddField(
            model_name='crate',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='unittype',
            unique_together={('manufacturer', 'model')},
        ),
        migrations.AddField(
            model_name='crate',
            name='shipping_agent',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='unittype',
            index=models.Index(fields=['manufacturer', 'model'], name='lsdb_unitty_manufac_903e2f_idx'),
        ),
    ]
