# Generated by Django 3.0.8 on 2021-02-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0010_auto_20210222_2139'),
        #('lsdb', '0010_auto_20210216_2115'),
    ]

    operations = [
    ]
