# Generated by Django 3.0.8 on 2021-03-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0010_auto_20210222_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleproperty',
            name='bifacial',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurementresult',
            name='result_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
