# Generated by Django 3.0.8 on 2021-03-09 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0011_auto_20210305_0216'),
        ('lsdb', '0011_merge_20210223_0501'),
    ]

    operations = [
    ]
