# Generated by Django 3.0.8 on 2021-03-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0012_merge_20210309_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduletechnology',
            name='diode_ideality_factor',
            field=models.FloatField(default=0),
        ),
    ]
