# Generated by Django 3.0.8 on 2021-03-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0013_moduletechnology_diode_ideality_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_types',
            field=models.ManyToManyField(blank=True, to='lsdb.AssetType'),
        ),
        migrations.AddField(
            model_name='unit',
            name='disposition',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='lsdb.Disposition'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obsolete_asset_type', to='lsdb.AssetType'),
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='notes',
            new_name='old_notes',
        ),
        migrations.AddField(
            model_name='unit',
            name='notes',
            field=models.ManyToManyField(blank=True, to='lsdb.Note'),
        ),
    ]
