# Generated by Django 3.0.8 on 2021-03-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0015_auto_20210330_2258'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='lsdb_asset_asset_t_220646_idx',
        ),
        migrations.AddField(
            model_name='proceduredefinition',
            name='project_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proceduredefinition',
            name='aggregate_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('name', 'location')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name', 'location'], name='lsdb_asset_name_c9050d_idx'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
    ]
