# Generated by Django 3.0.8 on 2021-04-08 18:08

from django.db import migrations, models

def initialize_tib(apps, schema_editor):
    WorkOrder = apps.get_model('lsdb', 'WorkOrder')
    WorkOrder = WorkOrder()
    work_orders = WorkOrder.objects.all()
    for work_order in work_orders:
        if work_order.units.all():
            for unit in work_order.units.all():
                unit.tib = work_order.tib
                unit.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0017_auto_20210402_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='tib',
            field=models.BooleanField(blank=True, null=True),
        ),
        # Can't run this here: Need to do this manually
        # migrations.RunPython(initialize_tib),
        migrations.AddField(
            model_name='crate',
            name='work_orders',
            field=models.ManyToManyField(blank=True, to='lsdb.WorkOrder'),
        ),
    ]
