# Generated by Django 3.0.8 on 2021-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0018_unit_tib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedureresult',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='procedureresult',
            name='version',
            field=models.CharField(max_length=64),
        ),
    ]
