# Generated by Django 3.2 on 2021-06-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0021_auto_20210623_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='unit_disposition',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='unitdisposition', to='lsdb.disposition'),
        ),
            migrations.AddField(
            model_name='procedureexecutionorder',
            name='execution_condition',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.AddField(
            model_name='procedureresult',
            name='notes',
            field=models.ManyToManyField(blank=True, to='lsdb.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='disposition',
            field=models.ForeignKey(default=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='lsdb.disposition'),
        ),
    ]
