# Generated by Django 3.2 on 2021-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0022_workorder_unit_disposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsequencedefinition',
            name='short_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
