# Generated by Django 3.2 on 2021-08-23 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsdb', '0024_auto_20210816_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetype',
            name='groups',
            field=models.ManyToManyField(blank=True, to='lsdb.Group'),
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('review_datetime', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=32)),
                ('source_code', models.TextField(blank=True, null=True)),
                ('byte_code', models.TextField(blank=True, null=True)),
                ('restricted', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsdb.disposition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsdb.group')),
                ('reviewed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_reviewed_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'version'),
            },
        ),
    ]
