# Generated by Django 3.2 on 2021-09-07 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsdb', '0025_auto_20210823_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='reviewed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_reviewed_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
