# Generated by Django 3.2 on 2021-10-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0026_auto_20210907_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurefile',
            name='hash_algorithm',
            field=models.CharField(choices=[['md5', 'md5'], ['sha1', 'sha1'], ['sha256', 'sha256'], ['sha3_512', 'sha3_512'], ['sha512', 'sha512']], default='sha256', max_length=32),
        ),
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
    ]
