# Generated by Django 3.2 on 2021-10-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0028_auto_20211104_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='short_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
