# Generated by Django 3.2 on 2021-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsdb', '0027_auto_20211014_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.AlterField(
            model_name='procedureexecutionorder',
            name='execution_group_number',
            field=models.FloatField(),
        ),
    ]
