# Generated by Django 3.2 on 2021-12-28 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsdb', '0028_auto_20211026_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('body_source', models.TextField(blank=True, null=True)),
                ('subject_source', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsdb.disposition')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsdb.fileformat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsdb.group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
