# Generated by Django 3.2 on 2022-01-13 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsdb', '0029_auto_20211228_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_templates',
            field=models.ManyToManyField(blank=True, to='lsdb.Template'),
        ),
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, to='lsdb.Label'),
        ),
        migrations.AddField(
            model_name='testsequencedefinition',
            name='hex_color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

    ]
